nirps_ha_online: ../manual_trigger/nirps_ha_profile_online.yaml
nirps_ha_offline: ../manual_trigger/nirps_ha_profile_offline.yaml

nirps_he_online: ../manual_trigger/nirps_he_profile_online.yaml
nirps_ha_online: ../manual_trigger/nirps_he_profile_offline.yaml

spirou_online: ../manual_trigger/spirou_online.yaml
spirou_offline: ../manual_trigger/spirou_offline.yaml

# whether to run in test mode
test: False
# the valid time period for files in days
valid time: 7
# the file size limit in GB
file size limit: 10
# local directory to save tar files to (should not contain anything else)
local path: /cosmos99/nirps/apero-data/misc/apero-request/
# email address to send from
email from: nirps-client@astro.umontreal.ca
# SSH PATH to copy the website to
ssh:
  directory: /export/www/home/cook/www/apero-drs/requests/
  user: cook
  host: venus.astro.umontreal.ca
  options: ssh -oport=5822
  url: http://apero.exoplanets.ca/requests/