nirps ha V0.7.275 ref cal:
    apero profile: /nirps_raw/nirps/apero-data/drs-settings/setup_07254_nirps_ha
    lbl in path: /space/spirou/obj_full_NIRPS_HA
    lbl path: /space/spirou/LBL/NIRPS_HA
    raw dir: /nirps_raw/nirps/apero-data/common/rawsym202211-HA

nirps ha V0.7.275 per night cal:
    apero profile: /nirps_raw/nirps/apero-data/drs-settings/setup_07254_nirpsha_pernight
    lbl in path: /space/spirou/obj_full_NIRPS_HA_per_night
    lbl path: /space/spirou/LBL/NIRPS_HA_pernight
    raw dir: /nirps_raw/nirps/apero-data/common/rawsym202211-HA

nirps he V0.7.275 ref cal:
    apero profile: /nirps_raw/nirps/apero-data/drs-settings/setup_07254_nirps_he
    lbl in path: /space/spirou/obj_full_NIRPS_HE
    lbl path: /space/spirou/LBL/NIRPS_HE
    raw dir: /nirps_raw/nirps/apero-data/common/rawsym202211-HE

nirps he V0.7.275 per night cal:
    apero profile: /nirps_raw/nirps/apero-data/drs-settings/setup_07254_nirpshe_pernight
    lbl in path: /space/spirou/obj_full_NIRPS_HE_per_night
    lbl path: /space/spirou/LBL/NIRPS_HE_pernight
    raw dir: /nirps_raw/nirps/apero-data/common/rawsym202211-HE