[nirps.nirps_he_minidata_07295]
module load StdEnv/2020 python/3.9 hdf5
source /project/6102120/apero/nirps_bin/env/apero_drs_07/bin/activate
source /project/6102120/apero/nirps_bin/settings/nirps_he_minidata_07295/nirps_he_minidata_07295.bash.setup
cd /project/6102120/apero/

[nirps.general_07]
module load StdEnv/2020 python/3.9 hdf5
source /project/6102120/apero/nirps_bin/env/apero_drs_07/bin/activate

[spirou.spirou_mini2_07295]
module load StdEnv/2020 python/3.9 hdf5
source /project/6102120/apero/spirou_bin/env/apero_drs_07/bin/activate
source /project/6102120/apero/spirou_bin/settings/spirou_mini2_07295/spirou_mini2_07295.bash.setup
cd /project/6102120/apero/

[spirou.spirou_offline_07_old]
module load StdEnv/2020 python/3.9 hdf5
source /project/6102120/apero/spirou_bin/env/apero_drs_07_old/bin/activate
source /project/6102120/apero/spirou_bin/settings/spirou_offline_07/spirou_offline_07.bash.setup

[spirou.spirou_offline_07]
module load StdEnv/2023 python/3.12 hdf5 cmake/3.31.0
source /project/6102120/apero/spirou_bin/env/apero_drs_07/bin/activate
source /project/6102120/apero/spirou_bin/settings/spirou_offline_07/spirou_offline_07.bash.setup

[spirou.general_07]
module load StdEnv/2023 python/3.12 hdf5 cmake/3.31.0
source /project/6102120/apero/spirou_bin/env/apero_drs_07/bin/activate

[spirou.spirou_mini2_08xxx]
module load StdEnv/2023 python/3.12 hdf5 cmake/3.31.0 gcc opencv/4.13.0
source /project/6102120/apero/spirou_bin/env/apero_drs_08/bin/activate
source apero_profile.sh spirou_mini2_08xxx

[spirou.spirou_mini2_07xxx]
module load StdEnv/2023 python/3.12 hdf5 cmake/3.31.0 gcc opencv/4.13.0
source /project/6102120/apero/spirou_bin/env/apero_drs_07/bin/activate
source /project/6102120/apero/spirou_bin/settings/spirou_mini2_07xxx/spirou_mini2_07xxx.bash.setup